"use strict";var sjcl={cipher:{},hash:{},keyexchange:{},mode:{},misc:{},codec:{},exception:{corrupt:function(d){this.toString=function(){return"CORRUPT: "+this.message};this.message=d},invalid:function(d){this.toString=function(){return"INVALID: "+this.message};this.message=d},bug:function(d){this.toString=function(){return"BUG: "+this.message};this.message=d},notReady:function(d){this.toString=function(){return"NOT READY: "+this.message};this.message=d}}};
sjcl.cipher.aes=function(d){this.c[0][0][0]||this.j();var b,c,a,e,f=this.c[0][4],h=this.c[1];b=d.length;var g=1;if(4!==b&&6!==b&&8!==b)throw new sjcl.exception.invalid("invalid aes key size");this.h=[a=d.slice(0),e=[]];for(d=b;d<4*b+28;d++){c=a[d-1];if(0===d%b||8===b&&4===d%b)c=f[c>>>24]<<24^f[c>>16&255]<<16^f[c>>8&255]<<8^f[c&255],0===d%b&&(c=c<<8^c>>>24^g<<24,g=g<<1^283*(g>>7));a[d]=a[d-b]^c}for(b=0;d;b++,d--)c=a[b&3?d:d-4],e[b]=4>=d||4>b?c:h[0][f[c>>>24]]^h[1][f[c>>16&255]]^h[2][f[c>>8&255]]^h[3][f[c&
255]]};
sjcl.cipher.aes.prototype={encrypt:function(d){return w(this,d,0)},decrypt:function(d){return w(this,d,1)},c:[[[],[],[],[],[]],[[],[],[],[],[]]],j:function(){var d=this.c[0],b=this.c[1],c=d[4],a=b[4],e,f,h,g=[],k=[],l,p,m,n;for(e=0;0x100>e;e++)k[(g[e]=e<<1^283*(e>>7))^e]=e;for(f=h=0;!c[f];f^=l||1,h=k[h]||1)for(m=h^h<<1^h<<2^h<<3^h<<4,m=m>>8^m&255^99,c[f]=m,a[m]=f,p=g[e=g[l=g[f]]],n=0x1010101*p^0x10001*e^0x101*l^0x1010100*f,p=0x101*g[m]^0x1010100*m,e=0;4>e;e++)d[e][f]=p=p<<24^p>>>8,b[e][m]=n=n<<24^n>>>8;for(e=
0;5>e;e++)d[e]=d[e].slice(0),b[e]=b[e].slice(0)}};
function w(d,b,c){if(4!==b.length)throw new sjcl.exception.invalid("invalid aes block size");var a=d.h[c],e=b[0]^a[0],f=b[c?3:1]^a[1],h=b[2]^a[2];b=b[c?1:3]^a[3];var g,k,l,p=a.length/4-2,m,n=4,r=[0,0,0,0];g=d.c[c];d=g[0];var q=g[1],t=g[2],u=g[3],v=g[4];for(m=0;m<p;m++)g=d[e>>>24]^q[f>>16&255]^t[h>>8&255]^u[b&255]^a[n],k=d[f>>>24]^q[h>>16&255]^t[b>>8&255]^u[e&255]^a[n+1],l=d[h>>>24]^q[b>>16&255]^t[e>>8&255]^u[f&255]^a[n+2],b=d[b>>>24]^q[e>>16&255]^t[f>>8&255]^u[h&255]^a[n+3],n+=4,e=g,f=k,h=l;for(m=
0;4>m;m++)r[c?3&-m:m]=v[e>>>24]<<24^v[f>>16&255]<<16^v[h>>8&255]<<8^v[b&255]^a[n++],g=e,e=f,f=h,h=b,b=g;return r}
sjcl.bitArray={bitSlice:function(d,b,c){d=sjcl.bitArray.u(d.slice(b/32),32-(b&31)).slice(1);return void 0===c?d:sjcl.bitArray.clamp(d,c-b)},extract:function(d,b,c){var a=Math.floor(-b-c&31);return((b+c-1^b)&-32?d[b/32|0]<<32-a^d[b/32+1|0]>>>a:d[b/32|0]>>>a)&(1<<c)-1},concat:function(d,b){if(0===d.length||0===b.length)return d.concat(b);var c=d[d.length-1],a=sjcl.bitArray.getPartial(c);return 32===a?d.concat(b):sjcl.bitArray.u(b,a,c|0,d.slice(0,d.length-1))},bitLength:function(d){var b=d.length;return 0===
b?0:32*(b-1)+sjcl.bitArray.getPartial(d[b-1])},clamp:function(d,b){if(32*d.length<b)return d;d=d.slice(0,Math.ceil(b/32));var c=d.length;b=b&31;0<c&&b&&(d[c-1]=sjcl.bitArray.partial(b,d[c-1]&2147483648>>b-1,1));return d},partial:function(d,b,c){return 32===d?b:(c?b|0:b<<32-d)+0x10000000000*d},getPartial:function(d){return Math.round(d/0x10000000000)||32},equal:function(d,b){if(sjcl.bitArray.bitLength(d)!==sjcl.bitArray.bitLength(b))return!1;var c=0,a;for(a=0;a<d.length;a++)c|=d[a]^b[a];return 0===
c},u:function(d,b,c,a){var e;e=0;for(void 0===a&&(a=[]);32<=b;b-=32)a.push(c),c=0;if(0===b)return a.concat(d);for(e=0;e<d.length;e++)a.push(c|d[e]>>>b),c=d[e]<<32-b;e=d.length?d[d.length-1]:0;d=sjcl.bitArray.getPartial(e);a.push(sjcl.bitArray.partial(b+d&31,32<b+d?c:a.pop(),1));return a},A:function(d,b){return[d[0]^b[0],d[1]^b[1],d[2]^b[2],d[3]^b[3]]},byteswapM:function(d){var b,c;for(b=0;b<d.length;++b)c=d[b],d[b]=c>>>24|c>>>8&0xff00|(c&0xff00)<<8|c<<24;return d}};
sjcl.codec.utf8String={fromBits:function(d){var b="",c=sjcl.bitArray.bitLength(d),a,e;for(a=0;a<c/8;a++)0===(a&3)&&(e=d[a/4]),b+=String.fromCharCode(e>>>24),e<<=8;return decodeURIComponent(escape(b))},toBits:function(d){d=unescape(encodeURIComponent(d));var b=[],c,a=0;for(c=0;c<d.length;c++)a=a<<8|d.charCodeAt(c),3===(c&3)&&(b.push(a),a=0);c&3&&b.push(sjcl.bitArray.partial(8*(c&3),a));return b}};
sjcl.codec.bytes={fromBits:function(d){var b=[],c=sjcl.bitArray.bitLength(d),a,e;for(a=0;a<c/8;a++)0===(a&3)&&(e=d[a/4]),b.push(e>>>24),e<<=8;return b},toBits:function(d){var b=[],c,a=0;for(c=0;c<d.length;c++)a=a<<8|d[c],3===(c&3)&&(b.push(a),a=0);c&3&&b.push(sjcl.bitArray.partial(8*(c&3),a));return b}};sjcl.hash.sha256=function(d){this.h[0]||this.j();d?(this.i=d.i.slice(0),this.g=d.g.slice(0),this.b=d.b):this.reset()};sjcl.hash.sha256.hash=function(d){return(new sjcl.hash.sha256).update(d).finalize()};
sjcl.hash.sha256.prototype={blockSize:512,reset:function(){this.i=this.s.slice(0);this.g=[];this.b=0;return this},update:function(d){"string"===typeof d&&(d=sjcl.codec.utf8String.toBits(d));var b,c=this.g=sjcl.bitArray.concat(this.g,d);b=this.b;d=this.b=b+sjcl.bitArray.bitLength(d);if(0x1fffffffffffff<d)throw new sjcl.exception.invalid("Cannot hash more than 2^53 - 1 bits");if("undefined"!==typeof Uint32Array){var a=new Uint32Array(c),e=0;for(b=512+b-(512+b&0x1ff);b<=d;b+=512)x(this,a.subarray(16*e,
16*(e+1))),e+=1;c.splice(0,16*e)}else for(b=512+b-(512+b&0x1ff);b<=d;b+=512)x(this,c.splice(0,16));return this},finalize:function(){var d,b=this.g,c=this.i,b=sjcl.bitArray.concat(b,[sjcl.bitArray.partial(1,1)]);for(d=b.length+2;d&15;d++)b.push(0);b.push(Math.floor(this.b/0x100000000));for(b.push(this.b|0);b.length;)x(this,b.splice(0,16));this.reset();return c},s:[],h:[],j:function(){function d(a){return 0x100000000*(a-Math.floor(a))|0}for(var b=0,c=2,a,e;64>b;c++){e=!0;for(a=2;a*a<=c;a++)if(0===c%a){e=
!1;break}e&&(8>b&&(this.s[b]=d(Math.pow(c,.5))),this.h[b]=d(Math.pow(c,1/3)),b++)}}};
function x(d,b){var c,a,e,f=d.i,h=d.h,g=f[0],k=f[1],l=f[2],p=f[3],m=f[4],n=f[5],r=f[6],q=f[7];for(c=0;64>c;c++)16>c?a=b[c]:(a=b[c+1&15],e=b[c+14&15],a=b[c&15]=(a>>>7^a>>>18^a>>>3^a<<25^a<<14)+(e>>>17^e>>>19^e>>>10^e<<15^e<<13)+b[c&15]+b[c+9&15]|0),a=a+q+(m>>>6^m>>>11^m>>>25^m<<26^m<<21^m<<7)+(r^m&(n^r))+h[c],q=r,r=n,n=m,m=p+a|0,p=l,l=k,k=g,g=a+(k&l^p&(k^l))+(k>>>2^k>>>13^k>>>22^k<<30^k<<19^k<<10)|0;f[0]=f[0]+g|0;f[1]=f[1]+k|0;f[2]=f[2]+l|0;f[3]=f[3]+p|0;f[4]=f[4]+m|0;f[5]=f[5]+n|0;f[6]=f[6]+r|0;f[7]=
f[7]+q|0}
sjcl.mode.gcm={name:"gcm",encrypt:function(d,b,c,a,e){var f=b.slice(0);b=sjcl.bitArray;a=a||[];d=sjcl.mode.gcm.m(!0,d,f,a,c,e||128);return b.concat(d.data,d.tag)},decrypt:function(d,b,c,a,e){var f=b.slice(0),h=sjcl.bitArray,g=h.bitLength(f);e=e||128;a=a||[];e<=g?(b=h.bitSlice(f,g-e),f=h.bitSlice(f,0,g-e)):(b=f,f=[]);d=sjcl.mode.gcm.m(!1,d,f,a,c,e);if(!h.equal(d.tag,b))throw new sjcl.exception.corrupt("gcm: tag doesn't match");return d.data},w:function(d,b){var c,a,e,f,h,g=sjcl.bitArray.A;e=[0,0,0,
0];f=b.slice(0);for(c=0;128>c;c++){(a=0!==(d[Math.floor(c/32)]&1<<31-c%32))&&(e=g(e,f));h=0!==(f[3]&1);for(a=3;0<a;a--)f[a]=f[a]>>>1|(f[a-1]&1)<<31;f[0]>>>=1;h&&(f[0]^=-0x1f000000)}return e},a:function(d,b,c){var a,e=c.length;b=b.slice(0);for(a=0;a<e;a+=4)b[0]^=0xffffffff&c[a],b[1]^=0xffffffff&c[a+1],b[2]^=0xffffffff&c[a+2],b[3]^=0xffffffff&c[a+3],b=sjcl.mode.gcm.w(b,d);return b},m:function(d,b,c,a,e,f){var h,g,k,l,p,m,n,r,q=sjcl.bitArray;m=c.length;n=q.bitLength(c);r=q.bitLength(a);g=q.bitLength(e);
h=b.encrypt([0,0,0,0]);96===g?(e=e.slice(0),e=q.concat(e,[1])):(e=sjcl.mode.gcm.a(h,[0,0,0,0],e),e=sjcl.mode.gcm.a(h,e,[0,0,Math.floor(g/0x100000000),g&0xffffffff]));g=sjcl.mode.gcm.a(h,[0,0,0,0],a);p=e.slice(0);a=g.slice(0);d||(a=sjcl.mode.gcm.a(h,g,c));for(l=0;l<m;l+=4)p[3]++,k=b.encrypt(p),c[l]^=k[0],c[l+1]^=k[1],c[l+2]^=k[2],c[l+3]^=k[3];c=q.clamp(c,n);d&&(a=sjcl.mode.gcm.a(h,g,c));d=[Math.floor(r/0x100000000),r&0xffffffff,Math.floor(n/0x100000000),n&0xffffffff];a=sjcl.mode.gcm.a(h,a,d);k=b.encrypt(e);
a[0]^=k[0];a[1]^=k[1];a[2]^=k[2];a[3]^=k[3];return{tag:q.bitSlice(a,0,f),data:c}}};sjcl.misc.hmac=function(d,b){this.o=b=b||sjcl.hash.sha256;var c=[[],[]],a,e=b.prototype.blockSize/32;this.f=[new b,new b];d.length>e&&(d=b.hash(d));for(a=0;a<e;a++)c[0][a]=d[a]^909522486,c[1][a]=d[a]^1549556828;this.f[0].update(c[0]);this.f[1].update(c[1]);this.l=new b(this.f[0])};
sjcl.misc.hmac.prototype.encrypt=sjcl.misc.hmac.prototype.mac=function(d){if(this.v)throw new sjcl.exception.invalid("encrypt on already updated hmac called!");this.update(d);return this.digest(d)};sjcl.misc.hmac.prototype.reset=function(){this.l=new this.o(this.f[0]);this.v=!1};sjcl.misc.hmac.prototype.update=function(d){this.v=!0;this.l.update(d)};sjcl.misc.hmac.prototype.digest=function(){var d=this.l.finalize(),d=(new this.o(this.f[1])).update(d).finalize();this.reset();return d};
sjcl.misc.pbkdf2=function(d,b,c,a,e){c=c||1E4;if(0>a||0>c)throw new sjcl.exception.invalid("invalid params to pbkdf2");"string"===typeof d&&(d=sjcl.codec.utf8String.toBits(d));"string"===typeof b&&(b=sjcl.codec.utf8String.toBits(b));e=e||sjcl.misc.hmac;d=new e(d);var f,h,g,k,l=[],p=sjcl.bitArray;for(k=1;32*l.length<(a||1);k++){e=f=d.encrypt(p.concat(b,[k]));for(h=1;h<c;h++)for(f=d.encrypt(f),g=0;g<f.length;g++)e[g]^=f[g];l=l.concat(e)}a&&(l=p.clamp(l,a));return l};
sjcl.misc.scrypt=function(d,b,c,a,e,f,h){var g=Math.pow(2,32)-1,k=sjcl.misc.scrypt;c=c||16384;a=a||8;e=e||1;if(a*e>=Math.pow(2,30))throw sjcl.exception.invalid("The parameters r, p must satisfy r * p < 2^30");if(2>c||c&0!=c-1)throw sjcl.exception.invalid("The parameter N must be a power of 2.");if(c>g/128/a)throw sjcl.exception.invalid("N too big.");if(a>g/128/e)throw sjcl.exception.invalid("r too big.");b=sjcl.misc.pbkdf2(d,b,1,128*e*a*8,h);a=b.length/e;k.reverse(b);for(g=0;g<e;g++){var l=b.slice(g*
a,(g+1)*a);k.blockcopy(k.ROMix(l,c),0,b,g*a)}k.reverse(b);return sjcl.misc.pbkdf2(d,b,1,f,h)};
sjcl.misc.scrypt.salsa20Core=function(d,b){function c(a,b){return a<<b|a>>>32-b}for(var a=d.slice(0),e=b;0<e;e-=2)a[4]^=c(a[0]+a[12],7),a[8]^=c(a[4]+a[0],9),a[12]^=c(a[8]+a[4],13),a[0]^=c(a[12]+a[8],18),a[9]^=c(a[5]+a[1],7),a[13]^=c(a[9]+a[5],9),a[1]^=c(a[13]+a[9],13),a[5]^=c(a[1]+a[13],18),a[14]^=c(a[10]+a[6],7),a[2]^=c(a[14]+a[10],9),a[6]^=c(a[2]+a[14],13),a[10]^=c(a[6]+a[2],18),a[3]^=c(a[15]+a[11],7),a[7]^=c(a[3]+a[15],9),a[11]^=c(a[7]+a[3],13),a[15]^=c(a[11]+a[7],18),a[1]^=c(a[0]+a[3],7),a[2]^=
c(a[1]+a[0],9),a[3]^=c(a[2]+a[1],13),a[0]^=c(a[3]+a[2],18),a[6]^=c(a[5]+a[4],7),a[7]^=c(a[6]+a[5],9),a[4]^=c(a[7]+a[6],13),a[5]^=c(a[4]+a[7],18),a[11]^=c(a[10]+a[9],7),a[8]^=c(a[11]+a[10],9),a[9]^=c(a[8]+a[11],13),a[10]^=c(a[9]+a[8],18),a[12]^=c(a[15]+a[14],7),a[13]^=c(a[12]+a[15],9),a[14]^=c(a[13]+a[12],13),a[15]^=c(a[14]+a[13],18);for(e=0;16>e;e++)d[e]=a[e]+d[e]};
sjcl.misc.scrypt.blockMix=function(d){for(var b=d.slice(-16),c=[],a=d.length/16,e=sjcl.misc.scrypt,f=0;f<a;f++)e.blockxor(d,16*f,b,0,16),e.salsa20Core(b,8),0==(f&1)?e.blockcopy(b,0,c,8*f):e.blockcopy(b,0,c,8*(f^1+a));return c};sjcl.misc.scrypt.ROMix=function(d,b){for(var c=d.slice(0),a=[],e=sjcl.misc.scrypt,f=0;f<b;f++)a.push(c.slice(0)),c=e.blockMix(c);for(f=0;f<b;f++)e.blockxor(a[c[c.length-16]&b-1],0,c,0),c=e.blockMix(c);return c};
sjcl.misc.scrypt.reverse=function(d){for(var b in d){var c=d[b]&255,c=c<<8|d[b]>>>8&255,c=c<<8|d[b]>>>16&255,c=c<<8|d[b]>>>24&255;d[b]=c}};sjcl.misc.scrypt.blockcopy=function(d,b,c,a,e){var f;e=e||d.length-b;for(f=0;f<e;f++)c[a+f]=d[b+f]|0};sjcl.misc.scrypt.blockxor=function(d,b,c,a,e){var f;e=e||d.length-b;for(f=0;f<e;f++)c[a+f]=c[a+f]^d[b+f]|0};"undefined"!==typeof module&&module.exports&&(module.exports=sjcl);"function"===typeof define&&define([],function(){return sjcl});
